### ISSUE TITLE
How will this work with geography based used cases (e.g. Geo-filtering / Geo-access)?

### ISSUE THREAD

**Issue by KenjiBaheux** [buettner/private-prefetch-proxy#1]
IP address can be used for geography based features such as filtering or restricting access to region locked content, etc.

On prefetches handled by a privacy prefetch proxy, the IP visible by CDN/websites will be the proxy's IP address, not the user's IP address.

**Comment by KenjiBaheux** [comment]
For regional locks and other features that depends on a location derived from the user's IP address, the following options come to mind:
 - Perform a check at navigation time (e.g. a sub-resource or JS request which will have the user's IP address).
 - Using a private prefetch proxy that's located in the same geo (country level) as the user.
 - Reject the prefetching requests (`Purpose: prefetch` HTTP header) for content that's known to be subject to geo conditions.

**Comment by jeremyroman** [comment]
I guess the fourth option would be for the client or proxy to resolve the geography to some large granularity (e.g. country) and send that information somewhere.
