### ISSUE TITLE
Example traffic-advice file content for Google

### ISSUE THREAD

**Issue by szepeviktor** [buettner/private-prefetch-proxy#21]
```
74.125.208.13 - - [18/Jun/2021:23:29:09 +0000] "GET /.well-known/traffic-advice HTTP/1.1" 404 5596 "-" "Chrome Privacy Preserving Prefetch Proxy"
```

I already receive requests for this file.
@jeremyroman Could you provide some simple examples for Google/bot?

**Comment by jeremyroman** [comment]
If you're okay with the default behavior, you don't need to do anything. Returning 404 is perfectly valid.

You can provide this file (with the MIME type `application/trafficadvice+json`) if you wish to modify it. For example, if you wanted to expressly allow traffic from any prefetch proxy, you could write:

```json
[{"user_agent": "prefetch-proxy", "disallow": false}]
```

This traffic is related not to Googlebot (the crawler), but determining whether user prefetch traffic from search results should be allowed.

**Comment by szepeviktor** [comment]
Thank you.

For Apache

```apache
RewriteRule "^/\.well-known/traffic-advice$" - [T=application/trafficadvice+json,END]
```

**Comment by jasomdotnet** [comment]
This example allow "Chrome Privacy Preserving Prefetch Proxy" to Prefetch without limitations:
```
[{
  "user_agent": "prefetch-proxy",
  "google_prefetch_proxy_eap": {
    "fraction": 1.0
  }
}]
```
Thanks @szepeviktor for Apache config, I used it in my [article](https://www.jasom.net/private-prefetch-proxy-well-known-traffic-advice-apache-htaccess-nginx/). This code (ehm, my own work) represents config for right MIME type on Nginx:

```
# Chrome Privacy Preserving Prefetch Proxy
location /.well-known/traffic-advice {
   types { } default_type "application/trafficadvice+json; charset=utf-8";
}
```
