### ISSUE TITLE
Missing tool testing traffic-advice for my websites

### ISSUE THREAD

**Issue by jasomdotnet** [buettner/private-prefetch-proxy#28]
Hi,
I just [configured](https://www.jasom.net/private-prefetch-proxy-well-known-traffic-advice-apache-htaccess-nginx/) several sites "to give" traffic-advice. I'm missing tool where I can test if file is valid (has right MIME type and content).

**Comment by buettner** [comment]
Would this help?

https://traffic-advice-checkup.netlify.app/

**Comment by jasomdotnet** [comment]
I have updated my article with tip to this tool, tnx.
